export enum CollectionConstans {
  // ALL COLLECTIONS
  ALL_COLLECTION_REQUEST = "ALL_COLLECTION_REQUEST",
  ALL_COLLECTION_SUCCESS = "ALL_COLLECTION_SUCCESS",
  ALL_COLLECTION_FAIL = "ALL_COLLECTION_FAIL",

  // NEW COLLECTION
  NEW_COLLECTION_REQUEST = "NEW_COLLECTION_REQUEST",
  NEW_COLLECTION_SUCCESS = "NEW_COLLECTION_SUCCESS",
  NEW_COLLECTION_RESET = "NEW_COLLECTION_RESET",
  NEW_COLLECTION_FAIL = "NEW_COLLECTION_FAIL",

  // COLLECTION DETAILS
  COLLECTION_DETAILS_REQUEST = "COLLECTION_DETAILS_REQUEST",
  COLLECTION_DETAILS_SUCCESS = "COLLECTION_DETAILS_SUCCESS",
  COLLECTION_DETAILS_FAIL = "COLLECTION_DETAILS_FAIL",

  // DELETE COLLECTION
  DELETE_COLLECTION_REQUEST = "DELETE_COLLECTION_REQUEST",
  DELETE_COLLECTION_SUCCESS = "DELETE_COLLECTION_SUCCESS",
  DELETE_COLLECTION_RESET = "DELETE_COLLECTION_RESET",
  DELETE_COLLECTION_FAIL = "DELETE_COLLECTION_FAIL",
  // COMMON
  CLEAR_ERRORS = "CLEAR_ERRORS",
}
