export enum ProductConstants {
    // ALL PRODUCTS
    ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST",
    ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS",
    ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL",

    // ADMIN PRODUCTS
    ADMIN_PRODUCT_REQUEST = "ADMIN_PRODUCT_REQUEST",
    ADMIN_PRODUCT_SUCCESS = "ADMIN_PRODUCT_SUCCESS",
    ADMIN_PRODUCT_FAIL = "ADMIN_PRODUCT_FAIL",

    // NEW PRODUCT
    NEW_PRODUCT_REQUEST = "NEW_PRODUCT_REQUEST",
    NEW_PRODUCT_SUCCESS = "NEW_PRODUCT_SUCCESS",
    NEW_PRODUCT_RESET = "NEW_PRODUCT_RESET",
    NEW_PRODUCT_FAIL = "NEW_PRODUCT_FAIL",

    // UPDATE PRODUCT
    UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST",
    UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS",
    UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET",
    UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL",

    // DELETE PRODUCT
    DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST",
    DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS",
    DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET",
    DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL",

    // PRODUCT DETAILS
    PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST",
    PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS",
    PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL",

    // NEW REVIEW
    NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST",
    NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS",
    NEW_REVIEW_RESET = "NEW_REVIEW_RESET",
    NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL",

    // ALL REVIEWS
    ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST",
    ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS",
    ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL",

    // DELETE REVIEW
    DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST",
    DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS",
    DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET",
    DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL",

    // COMMON
    CLEAR_ERRORS = "CLEAR_ERRORS"
}
